export const FIND_PRODUCT_BY_ID_REQUEST="FIND_PRODUCT_BY_ID_REQUEST";
export const FIND_PRODUCT_BY_ID_SUCCESS="FIND_PRODUCT_BY_ID_SUCCESS";
export const FIND_PRODUCT_BY_ID_FAILURE="FIND_PRODUCT_BY_ID_FAILURE";


export const FIND_PRODUCT_REQUEST="FIND_PRODUCT_CATEGOY_REQUEST";
export const FIND_PRODUCT_SUCCESS="FIND_PRODUCT_CATEGORY_SUCCESS";
export const FIND_PRODUCT_FAILURE="FIND_PRODUCT_CATEGORY_FAILURE";


export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE';


export const EDIT_PRODUCT_REQUEST = 'EDIT_PRODUCT_REQUEST';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
export const EDIT_PRODUCT_FAILURE = 'EDIT_PRODUCT_FAILURE';


export const FETCH_TOP_PRODUCTS_REQUEST = 'FETCH_TOP_PRODUCTS_REQUEST';
export const FETCH_TOP_PRODUCTS_SUCCESS = 'FETCH_TOP_PRODUCTS_SUCCESS';
export const FETCH_TOP_PRODUCTS_FAILURE = 'FETCH_TOP_PRODUCTS_FAILURE';